---
version: "2.1"
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    hostname: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${URL}
      - SUBDOMAINS=${SUBDOMAINS},
      - VALIDATION=${VALIDATION}
      - EMAIL=${EMAIL}
      - DHLEVEL=${DHLEVEL}
      - ONLY_SUBDOMAINS=${ONLY_SUBDOMAINS}
      - STAGING=${STAGING}
    networks:
      nextcloud-network:
        aliases:
          - letsencrypt
    volumes:
      - ./letsencrypt/config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: always
    
  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=$(ROOTPASS}
      - TZ=Asia/Colombo
      - MYSQL_DATABASE=$(DBNAME} 
      - MYSQL_USER=${DBUSER} 
      - MYSQL_PASSWORD=${DBPASS}
    networks:
      nextcloud-network:
        aliases:
          - mariadb
    volumes:
      - ./mariadb/config:/config
    ports:
      - 3306:3306
    restart: restart
  
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Colombo
    volumes:
      - ./nextcloud/config:/config
      - ./nextcloud/data:/data
    ports:
      - 443:443
    restart: restart
 
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Colombo
      - CLI_ARGS= #optional
    volumes:
      - ./duplicati/config:/config
      - /opt/backups:/backups
      - /opt/nextcloud:/source
    ports:
      - 8200:8200
    restart: restart
networks:
  nextcloud-network:
    driver: bridge
    
