---
version: "2.1"
services:
  swag:
    image: linuxserver/swag
    container_name: swag
    hostname: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${URL}
      - SUBDOMAINS=${SUBDOMAINS},
      - VALIDATION=${VALIDATION}
      - EMAIL=${EMAIL}
      - DHLEVEL=${DHLEVEL}
      - ONLY_SUBDOMAINS=${ONLY_SUBDOMAINS}
      - STAGING=${STAGING}
    networks:
      nextcloud-network:
        aliases:
          - swag
    volumes:
      - ./swag/config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: always
    
  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    hostname: mariadb
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - MYSQL_ROOT_PASSWORD=${DBROOTPASS}
      - TZ=${TZ}
      - MYSQL_DATABASE=${DBNAME} 
      - MYSQL_USER=${DBUSER} 
      - MYSQL_PASSWORD=${DBPASS}
    networks:
      nextcloud-network:
        aliases:
          - mariadb
    volumes:
      - ./mariadb/config:/config
    ports:
      - 3306:3306
    restart: always
  
  mariadb-backup:
    container_name: mariadb-backup
    hostname: mariadb-backup
    image: tiredofit/db-backup
    links:
     - mariadb
    volumes:
      - ./mariadb/backups:/backup
    environment:
      - DB_TYPE=mariadb
      - DB_HOST=mariadb
      - DB_NAME=${DBNAME}
      - DB_USER=${DBUSER}
      - DB_PASS=${DBUSER}
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - MD5=TRUE
      - COMPRESSION=XZ
      - SPLIT_DB=FALSE
    networks:
      nextcloud-network:
        aliases:
          - mariadb-backup
    restart: always
  
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    hostname: nextcloud
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./nextcloud/config:/config
      - ./nextcloud/data:/data
    networks:
      nextcloud-network:
        aliases:
          - nextcloud
          
    ports:
      - 444:443
    restart: always
 
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    hostname: duplicati
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CLI_ARGS= #optional
    networks:
      nextcloud-network:
        aliases:
          - duplicati
    volumes:
      - ./duplicati/config:/config
      - /opt/backups:/backups
      - /opt/nextcloud:/source
    ports:
      - 8200:8200
    restart: always
    
  phpmyadmin:
    image: openemail/phpmyadmin
    container_name: phpmyadmin
    hostname: pma.${URL}
    restart: always
    environment:
      - TZ=${TZ}
      - PMA_HOST=mysql
      - PMA_ARBITRARY=1
      - PMA_ABSOLUTE_URI=https://${NEXTCLOUD_HOSTNAME}/phpmyadmin/
    networks:
      nextcloud-network:
        aliases:
          - phpmyadmin
networks:
  nextcloud-network:
    driver: bridge
      
